<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <VersionPrefix>1.2.4</VersionPrefix>
    <AssemblyVersion>1.2.4.0</AssemblyVersion>
    <FileVersion>1.2.4.0</FileVersion>
    <InformationalVersion>1.2.4</InformationalVersion>
    <Company>CouchCTRL</Company>
    <Product>CouchCTRL Windows Companion</Product>
    <Authors>CouchCTRL</Authors>
    <Copyright>Copyright CouchCTRL</Copyright>
    <PackageProjectUrl>https://couchctrl.app</PackageProjectUrl>
  </PropertyGroup>
</Project>
